SET REFERENTIAL_INTEGRITY FALSE; DELETE FROM student WHERE id IN (SELECT mark.id FROM subject JOIN mark ON mark.id = subject.id WHERE subject.grade > 4);
SET REFERENTIAL_INTEGRITY FALSE; DELETE FROM student WHERE id IN (SELECT  s.id FROM student AS s JOIN mark AS m ON s.id = m.student_id WHERE m.mark < 4);
SET REFERENTIAL_INTEGRITY FALSE; DELETE FROM paymenttype WHERE name = 'DAILY';
SET REFERENTIAL_INTEGRITY FALSE; DELETE FROM mark WHERE mark < 7;